chirps/src/__init__.py
There was an error in the script.
It was updated.
=> chirps script was updated

cit_003_air_quality/contents/src/__init__.py
Convert ug/m3 to ppm for so2, no2, o3, and co
=> add unit conversion to cit_003_air_quality

foo_024_051_054_vegetation_health_products/Dockerfile, foo_024_051_054_vegetation_health_products/contents/src/__init__.py, foo_024_051_054_vegetation_health_products/start.sh
Updated the scale factor to 1/100th and fix two minor bugs.
=> Update scale factor

cit_003_air_quality/contents/src/__init__.py
Shortened these to what looks like includes at least a whole day of readings, but is 10X smaller.  Review code requested.
=> Changed MAXROWS from 5M to 500000 and change the MAX_PAGES to 15

soc_018_migrant_deaths/contents/src/__init__.py
There are still issues but was on debug
=> change error reporting

cli_012_co2_concentrations/Dockerfile, cli_039_spei/Dockerfile, foo_024_051_054_vegetation_health_products/Dockerfile
… there are other fixes that are necessary, but this is a start
=> Added RUN pip install oauth2client to each of these docker files

cli_039_spei/Dockerfile, cli_039_spei/contents/src/__init__.py, cli_039_spei/start.sh
Volume statement removed from the Dockerfile. Some small adjustments to the start.sh file formatting, and removing some comments to streamline the __init__.py code.
=> declaring the data folder as a volume was causing a permissioning error

foo_024_051_054_vegetation_health_products/contents/src/__init__.py
Changed file location url due to source change (can see original after the #)
=> changed file due to source change

dis_001_significant_earthquakes/Dockerfile, dis_001_significant_earthquakes/contents/src/__init__.py
- Switch to Alpine base
- Reduce maxrows -> 500k
- Iterate most recent to oldest instead of oldest to most recent
- Reduce from 31 day windows to 7 day windows to avoid 'too many results' errors###
=> Fix dis_001 request.json() errors

ene_008_oil_chemical_spill_incidents/Dockerfile, ene_008_oil_chemical_spill_incidents/contents/src/__init__.py, ene_008_oil_chemical_spill_incidents/start.sh
- minor refactor
- switch to alpine base
=> ene_008 Fix urllib request issue

cli_037_smoke_plumes_US/contents/src/__init__.py
- change url to pull from http:// rather than ftp://
- reduce error output for non-existing data to warnings
=> cli_037 reduce error output

soc_018_migrant_deaths/Dockerfile, soc_018_migrant_deaths/contents/src/__init__.py
- alpine base image
- switch from xls to csv
- remove dependencies
- iterate 1 year at a time, don't check previous years if no new data
- less flexible date parsing (expect consistent format)
=> Refactor soc_018 to address key errors

cit_003_air_quality/contents/src/__init__.py
Maybe will help with connection errors.
=> cit_003 AQ switch from GET to POST

soc_018_migrant_deaths/contents/src/__init__.py
Updated table headers to match Carto Table.
=> soc_018_update_table_headers

cit_035_tropomi_atmospheric_chemistry_model/contents/src/__init__.py
put different component variables in single parent folder
=> cit_035_tropomi_atmospheric_chemistry_model_parent_folder

update_nrt_timestamps/Dockerfile
=> change_oauth_version

cit_002_gmao_air_quality/contents/src/__init__.py
=> reduce upload timeout for ee upload

ocn_007_coral_bleaching_monitoring/contents/src/__init__.py
Errors corrected relating to numeric types and espcially nodata values--there are problems in the GEE Python API itself that surfaced in this instance.
=> ocn.007 fix

cli_043_arctic_ice/README.md, cli_043_arctic_ice/contents/src/__init__.py
The script stopped working since the download link and the format of the original data file have changed. Fixed those and updated the readme. Deleted the input variable 'url' from the tryRetrieveData function since it has never been used.
=> Fix cli 043 arctic ice

soc_018_migrant_deaths/Dockerfile, soc_018_migrant_deaths/contents/src/__init__.py
1. Fixing broken nrt script:
1. The original issue was that the dataset has rows with no coordinates which lead to a `break` statement to be triggered in the loop that processes the dataset row by row. Since the records with no coordinates was at the beginning of the file, it meant none of the new records were being read. This was fixed with 7069daff6487ed17a7704971dab9dbff9f0d149f
2. That uncovered an issue with rows later in the file that had missing dates which was causing the script to fail, so I added a check for a valid date. ba5b8fbc832f65361e1ccb55601c790ed1756171
3. Also, the url field is no longer a suable uid, so switched to `Main_ID` bc80e94f2474f54ea4b004c5f9f4e097cc534fac
4. More recently it seems they started using a 2 digit month in their url instead of 1 digit. That is …
=> soc_018_missing_migrants
